//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DAL.ManageDocument;
using DAL.ManageDocument.HelperClasses;
using DAL.ManageDocument.FactoryClasses;
using DAL.ManageDocument.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DAL.ManageDocument.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	
	/// <summary>Entity class which represents the entity 'ThongTinHoSo'.<br/><br/></summary>
	[Serializable]
	public partial class ThongTinHoSoEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
			
	{
		#region Class Member Declarations
		private LoaiBienDongEntity _loaiBienDong;
		private XaEntity _xa;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		
		#endregion

		#region Statics
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name LoaiBienDong</summary>
			public static readonly string LoaiBienDong = "LoaiBienDong";
			/// <summary>Member name Xa</summary>
			public static readonly string Xa = "Xa";
		}
		#endregion
		
		/// <summary> Static CTor for setting up custom property hashtables. Is executed before the first instance of this entity class or derived classes is constructed. </summary>
		static ThongTinHoSoEntity()
		{
			SetupCustomPropertyHashtables();
		}
		
		/// <summary> CTor</summary>
		public ThongTinHoSoEntity():base("ThongTinHoSoEntity")
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <remarks>For framework usage.</remarks>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ThongTinHoSoEntity(IEntityFields2 fields):base("ThongTinHoSoEntity")
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ThongTinHoSoEntity</param>
		public ThongTinHoSoEntity(IValidator validator):base("ThongTinHoSoEntity")
		{
			InitClassEmpty(validator, null);
		}
				
		/// <summary> CTor</summary>
		/// <param name="thongTinHoSoId">PK value for ThongTinHoSo which data should be fetched into this ThongTinHoSo object</param>
		/// <remarks>The entity is not fetched by this constructor. Use a DataAccessAdapter for that.</remarks>
		public ThongTinHoSoEntity(System.Int64 thongTinHoSoId):base("ThongTinHoSoEntity")
		{
			InitClassEmpty(null, null);
			this.ThongTinHoSoId = thongTinHoSoId;
		}

		/// <summary> CTor</summary>
		/// <param name="thongTinHoSoId">PK value for ThongTinHoSo which data should be fetched into this ThongTinHoSo object</param>
		/// <param name="validator">The custom validator object for this ThongTinHoSoEntity</param>
		/// <remarks>The entity is not fetched by this constructor. Use a DataAccessAdapter for that.</remarks>
		public ThongTinHoSoEntity(System.Int64 thongTinHoSoId, IValidator validator):base("ThongTinHoSoEntity")
		{
			InitClassEmpty(validator, null);
			this.ThongTinHoSoId = thongTinHoSoId;
		}

		/// <summary> Protected CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected ThongTinHoSoEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			if(SerializationHelper.Optimization != SerializationOptimization.Fast) 
			{
				_loaiBienDong = (LoaiBienDongEntity)info.GetValue("_loaiBienDong", typeof(LoaiBienDongEntity));
				if(_loaiBienDong!=null)
				{
					_loaiBienDong.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_xa = (XaEntity)info.GetValue("_xa", typeof(XaEntity));
				if(_xa!=null)
				{
					_xa.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				this.FixupDeserialization(FieldInfoProviderSingleton.GetInstance());
			}
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
			
		}

		
		/// <summary>Performs the desync setup when an FK field has been changed. The entity referenced based on the FK field will be dereferenced and sync info will be removed.</summary>
		/// <param name="fieldIndex">The fieldindex.</param>
		protected override void PerformDesyncSetupFKFieldChange(int fieldIndex)
		{
			switch((ThongTinHoSoFieldIndex)fieldIndex)
			{
				case ThongTinHoSoFieldIndex.LoaiBienDongId:
					DesetupSyncLoaiBienDong(true, false);
					break;
				case ThongTinHoSoFieldIndex.XaId:
					DesetupSyncXa(true, false);
					break;
				default:
					base.PerformDesyncSetupFKFieldChange(fieldIndex);
					break;
			}
		}

		/// <summary> Sets the related entity property to the entity specified. If the property is a collection, it will add the entity specified to that collection.</summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <param name="entity">Entity to set as an related entity</param>
		/// <remarks>Used by prefetch path logic.</remarks>
		protected override void SetRelatedEntityProperty(string propertyName, IEntityCore entity)
		{
			switch(propertyName)
			{
				case "LoaiBienDong":
					this.LoaiBienDong = (LoaiBienDongEntity)entity;
					break;
				case "Xa":
					this.Xa = (XaEntity)entity;
					break;
				default:
					this.OnSetRelatedEntityProperty(propertyName, entity);
					break;
			}
		}
		
		/// <summary>Gets the relation objects which represent the relation the fieldName specified is mapped on. </summary>
		/// <param name="fieldName">Name of the field mapped onto the relation of which the relation objects have to be obtained.</param>
		/// <returns>RelationCollection with relation object(s) which represent the relation the field is maped on</returns>
		protected override RelationCollection GetRelationsForFieldOfType(string fieldName)
		{
			return GetRelationsForField(fieldName);
		}

		/// <summary>Gets the relation objects which represent the relation the fieldName specified is mapped on. </summary>
		/// <param name="fieldName">Name of the field mapped onto the relation of which the relation objects have to be obtained.</param>
		/// <returns>RelationCollection with relation object(s) which represent the relation the field is maped on</returns>
		internal static RelationCollection GetRelationsForField(string fieldName)
		{
			RelationCollection toReturn = new RelationCollection();
			switch(fieldName)
			{
				case "LoaiBienDong":
					toReturn.Add(Relations.LoaiBienDongEntityUsingLoaiBienDongId);
					break;
				case "Xa":
					toReturn.Add(Relations.XaEntityUsingXaId);
					break;
				default:
					break;				
			}
			return toReturn;
		}

		/// <summary>Checks if the relation mapped by the property with the name specified is a one way / single sided relation. If the passed in name is null, it/ will return true if the entity has any single-sided relation</summary>
		/// <param name="propertyName">Name of the property which is mapped onto the relation to check, or null to check if the entity has any relation/ which is single sided</param>
		/// <returns>true if the relation is single sided / one way (so the opposite relation isn't present), false otherwise</returns>
		protected override bool CheckOneWayRelations(string propertyName)
		{
			int numberOfOneWayRelations = 0;
			switch(propertyName)
			{
				case null:
					return ((numberOfOneWayRelations > 0) || base.CheckOneWayRelations(null));
				default:
					return base.CheckOneWayRelations(propertyName);
			}
		}

		/// <summary> Sets the internal parameter related to the fieldname passed to the instance relatedEntity. </summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		/// <param name="fieldName">Name of field mapped onto the relation which resolves in the instance relatedEntity</param>
		protected override void SetRelatedEntity(IEntityCore relatedEntity, string fieldName)
		{
			switch(fieldName)
			{
				case "LoaiBienDong":
					SetupSyncLoaiBienDong(relatedEntity);
					break;
				case "Xa":
					SetupSyncXa(relatedEntity);
					break;
				default:
					break;
			}
		}

		/// <summary> Unsets the internal parameter related to the fieldname passed to the instance relatedEntity. Reverses the actions taken by SetRelatedEntity() </summary>
		/// <param name="relatedEntity">Instance to unset as the related entity of type entityType</param>
		/// <param name="fieldName">Name of field mapped onto the relation which resolves in the instance relatedEntity</param>
		/// <param name="signalRelatedEntityManyToOne">if set to true it will notify the manytoone side, if applicable.</param>
		protected override void UnsetRelatedEntity(IEntityCore relatedEntity, string fieldName, bool signalRelatedEntityManyToOne)
		{
			switch(fieldName)
			{
				case "LoaiBienDong":
					DesetupSyncLoaiBienDong(false, true);
					break;
				case "Xa":
					DesetupSyncXa(false, true);
					break;
				default:
					break;
			}
		}

		/// <summary> Gets a collection of related entities referenced by this entity which depend on this entity (this entity is the PK side of their FK fields). These entities will have to be persisted after this entity during a recursive save.</summary>
		/// <returns>Collection with 0 or more IEntity2 objects, referenced by this entity</returns>
		protected override List<IEntity2> GetDependingRelatedEntities()
		{
			List<IEntity2> toReturn = new List<IEntity2>();
			return toReturn;
		}
		
		/// <summary> Gets a collection of related entities referenced by this entity which this entity depends on (this entity is the FK side of their PK fields). These
		/// entities will have to be persisted before this entity during a recursive save.</summary>
		/// <returns>Collection with 0 or more IEntity2 objects, referenced by this entity</returns>
		protected override List<IEntity2> GetDependentRelatedEntities()
		{
			List<IEntity2> toReturn = new List<IEntity2>();
			if(_loaiBienDong!=null)
			{
				toReturn.Add(_loaiBienDong);
			}
			if(_xa!=null)
			{
				toReturn.Add(_xa);
			}
			return toReturn;
		}
		
		/// <summary>Gets a list of all entity collections stored as member variables in this entity. Only 1:n related collections are returned.</summary>
		/// <returns>Collection with 0 or more IEntityCollection2 objects, referenced by this entity</returns>
		protected override List<IEntityCollection2> GetMemberEntityCollections()
		{
			List<IEntityCollection2> toReturn = new List<IEntityCollection2>();
			return toReturn;
		}

		/// <summary>ISerializable member. Does custom serialization so event handlers do not get serialized. Serializes members of this entity class and uses the base class' implementation to serialize the rest.</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			if (SerializationHelper.Optimization != SerializationOptimization.Fast) 
			{
				info.AddValue("_loaiBienDong", (!this.MarkedForDeletion?_loaiBienDong:null));
				info.AddValue("_xa", (!this.MarkedForDeletion?_xa:null));
			}
			// __LLBLGENPRO_USER_CODE_REGION_START GetObjectInfo
			// __LLBLGENPRO_USER_CODE_REGION_END
			
			base.GetObjectData(info, context);
		}


				
		/// <summary>Gets a list of all the EntityRelation objects the type of this instance has.</summary>
		/// <returns>A list of all the EntityRelation objects the type of this instance has. Hierarchy relations are excluded.</returns>
		protected override List<IEntityRelation> GetAllRelations()
		{
			return new ThongTinHoSoRelations().GetAllRelations();
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'LoaiBienDong' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLoaiBienDong()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(LoaiBienDongFields.LoaiBienDongId, null, ComparisonOperator.Equal, this.LoaiBienDongId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Xa' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoXa()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(XaFields.XaId, null, ComparisonOperator.Equal, this.XaId));
			return bucket;
		}
		

		/// <summary>Creates a new instance of the factory related to this entity</summary>
		protected override IEntityFactory2 CreateEntityFactory()
		{
			return EntityFactoryCache2.GetEntityFactory(typeof(ThongTinHoSoEntityFactory));
		}

		/// <summary>Adds the member collections to the collections queue (base first)</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		protected override void AddToMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue) 
		{
			base.AddToMemberEntityCollectionsQueue(collectionsQueue);
		}
		
		/// <summary>Gets the member collections queue from the queue (base first)</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		protected override void GetFromMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue)
		{
			base.GetFromMemberEntityCollectionsQueue(collectionsQueue);

		}
		
		/// <summary>Determines whether the entity has populated member collections</summary>
		/// <returns>true if the entity has populated member collections.</returns>
		protected override bool HasPopulatedMemberEntityCollections()
		{
			bool toReturn = false;
			return toReturn ? true : base.HasPopulatedMemberEntityCollections();
		}
		
		/// <summary>Creates the member entity collections queue.</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		/// <param name="requiredQueue">The required queue.</param>
		protected override void CreateMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue, Queue<bool> requiredQueue) 
		{
			base.CreateMemberEntityCollectionsQueue(collectionsQueue, requiredQueue);
		}

		/// <summary>Gets all related data objects, stored by name. The name is the field name mapped onto the relation for that particular data element.</summary>
		/// <returns>Dictionary with per name the related referenced data element, which can be an entity collection or an entity or null</returns>
		protected override Dictionary<string, object> GetRelatedData()
		{
			Dictionary<string, object> toReturn = new Dictionary<string, object>();
			toReturn.Add("LoaiBienDong", _loaiBienDong);
			toReturn.Add("Xa", _xa);
			return toReturn;
		}

		/// <summary> Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			
			OnInitClassMembersComplete();
		}


		#region Custom Property Hashtable Setup
		/// <summary> Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ChiTietHoSo", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ChuyenVienId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ChuyenVienKiemTra", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("CongTyDoVe", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("CongTyDoVeId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("GhiChu", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("GioiTinhNguoiNop", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("HoSoMoiNhat", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("HoTen", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("KhoaChaId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("LichSuCapNhat", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("LoaiBienDongId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NgayChinhSua", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NgayHenTra", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NgayKiemTraNoiNghiep", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NgayNop", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NgayTraHoSo", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NguoiDungId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("NguoiNopHoSo", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("PhiDoVe", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("PhiThamDinh", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoBanVe", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoBienNhan", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoGiayTo", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoGiayToNguoiNop", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoHieuGiayChungNhan", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoHieuToBanDo", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SoThuTuThua", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ThongTinHoSoId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("XaId", fieldHashtable);
		}
		#endregion

		/// <summary> Removes the sync logic for member _loaiBienDong</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncLoaiBienDong(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _loaiBienDong, new PropertyChangedEventHandler(OnLoaiBienDongPropertyChanged), "LoaiBienDong", "ThongTinHoSos", DAL.ManageDocument.RelationClasses.StaticThongTinHoSoRelations.LoaiBienDongEntityUsingLoaiBienDongIdStatic, true, new int[] { (int)ThongTinHoSoFieldIndex.LoaiBienDongId });
		}

		/// <summary> setups the sync logic for member _loaiBienDong</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncLoaiBienDong(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _loaiBienDong, new PropertyChangedEventHandler( OnLoaiBienDongPropertyChanged ), "LoaiBienDong", "ThongTinHoSos", DAL.ManageDocument.RelationClasses.StaticThongTinHoSoRelations.LoaiBienDongEntityUsingLoaiBienDongIdStatic, true, new string[] {  }, new int[] { (int)ThongTinHoSoFieldIndex.LoaiBienDongId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnLoaiBienDongPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _xa</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncXa(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _xa, new PropertyChangedEventHandler(OnXaPropertyChanged), "Xa", "ThongTinHoSos", DAL.ManageDocument.RelationClasses.StaticThongTinHoSoRelations.XaEntityUsingXaIdStatic, true, new int[] { (int)ThongTinHoSoFieldIndex.XaId });
		}

		/// <summary> setups the sync logic for member _xa</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncXa(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _xa, new PropertyChangedEventHandler( OnXaPropertyChanged ), "Xa", "ThongTinHoSos", DAL.ManageDocument.RelationClasses.StaticThongTinHoSoRelations.XaEntityUsingXaIdStatic, true, new string[] {  }, new int[] { (int)ThongTinHoSoFieldIndex.XaId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnXaPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ThongTinHoSoEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();

			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END
			

			OnInitialized();

		}

		#region Class Property Declarations
		/// <summary> The relations object holding all relations of this entity with other entity classes.</summary>
		public  static ThongTinHoSoRelations Relations
		{
			get	{ return new ThongTinHoSoRelations(); }
		}
		
		/// <summary> The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties
		{
			get { return _customProperties;}
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LoaiBienDong' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLoaiBienDong
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(LoaiBienDongEntityFactory))),	(IEntityRelation)GetRelationsForField("LoaiBienDong")[0], (int)DAL.ManageDocument.EntityType.ThongTinHoSoEntity, (int)DAL.ManageDocument.EntityType.LoaiBienDongEntity, 0, null, null, null, null, "LoaiBienDong", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Xa' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathXa
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(XaEntityFactory))),	(IEntityRelation)GetRelationsForField("Xa")[0], (int)DAL.ManageDocument.EntityType.ThongTinHoSoEntity, (int)DAL.ManageDocument.EntityType.XaEntity, 0, null, null, null, null, "Xa", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}


		/// <summary> The custom properties for the type of this entity instance.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType
		{
			get { return CustomProperties;}
		}

		/// <summary> The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties
		{
			get { return _fieldsCustomProperties;}
		}

		/// <summary> The custom properties for the fields of the type of this entity instance. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType
		{
			get { return FieldsCustomProperties;}
		}

		/// <summary> The ChiTietHoSo property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."chiTietHoSo"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		
		public virtual System.String ChiTietHoSo
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.ChiTietHoSo, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.ChiTietHoSo, value); }
		}

		/// <summary> The ChuyenVienId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."chuyenVienId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Int32> ChuyenVienId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ThongTinHoSoFieldIndex.ChuyenVienId, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.ChuyenVienId, value); }
		}

		/// <summary> The ChuyenVienKiemTra property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."chuyenVienKiemTra"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String ChuyenVienKiemTra
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.ChuyenVienKiemTra, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.ChuyenVienKiemTra, value); }
		}

		/// <summary> The CongTyDoVe property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."congTyDoVe"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 1000<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String CongTyDoVe
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.CongTyDoVe, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.CongTyDoVe, value); }
		}

		/// <summary> The CongTyDoVeId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."congTyDoVeId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Int32> CongTyDoVeId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ThongTinHoSoFieldIndex.CongTyDoVeId, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.CongTyDoVeId, value); }
		}

		/// <summary> The GhiChu property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."ghiChu"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String GhiChu
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.GhiChu, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.GhiChu, value); }
		}

		/// <summary> The GioiTinhNguoiNop property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."gioiTinhNguoiNop"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Boolean> GioiTinhNguoiNop
		{
			get { return (Nullable<System.Boolean>)GetValue((int)ThongTinHoSoFieldIndex.GioiTinhNguoiNop, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.GioiTinhNguoiNop, value); }
		}

		/// <summary> The HoSoMoiNhat property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."hoSoMoiNhat"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		
		public virtual System.Boolean HoSoMoiNhat
		{
			get { return (System.Boolean)GetValue((int)ThongTinHoSoFieldIndex.HoSoMoiNhat, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.HoSoMoiNhat, value); }
		}

		/// <summary> The HoTen property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."hoTen"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String HoTen
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.HoTen, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.HoTen, value); }
		}

		/// <summary> The KhoaChaId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."khoaChaId"<br/>
		/// Table field type characteristics (type, precision, scale, length): BigInt, 19, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Int64> KhoaChaId
		{
			get { return (Nullable<System.Int64>)GetValue((int)ThongTinHoSoFieldIndex.KhoaChaId, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.KhoaChaId, value); }
		}

		/// <summary> The LichSuCapNhat property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."lichSuCapNhat"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String LichSuCapNhat
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.LichSuCapNhat, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.LichSuCapNhat, value); }
		}

		/// <summary> The LoaiBienDongId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."loaiBienDongId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Int32> LoaiBienDongId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ThongTinHoSoFieldIndex.LoaiBienDongId, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.LoaiBienDongId, value); }
		}

		/// <summary> The NgayChinhSua property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."ngayChinhSua"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.DateTime> NgayChinhSua
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ThongTinHoSoFieldIndex.NgayChinhSua, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NgayChinhSua, value); }
		}

		/// <summary> The NgayHenTra property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."ngayHenTra"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.DateTime> NgayHenTra
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ThongTinHoSoFieldIndex.NgayHenTra, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NgayHenTra, value); }
		}

		/// <summary> The NgayKiemTraNoiNghiep property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."ngayKiemTraNoiNghiep"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.DateTime> NgayKiemTraNoiNghiep
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ThongTinHoSoFieldIndex.NgayKiemTraNoiNghiep, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NgayKiemTraNoiNghiep, value); }
		}

		/// <summary> The NgayNop property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."ngayNop"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.DateTime> NgayNop
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ThongTinHoSoFieldIndex.NgayNop, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NgayNop, value); }
		}

		/// <summary> The NgayTraHoSo property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."ngayTraHoSo"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.DateTime> NgayTraHoSo
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ThongTinHoSoFieldIndex.NgayTraHoSo, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NgayTraHoSo, value); }
		}

		/// <summary> The NguoiDungId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."nguoiDungId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Int32> NguoiDungId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ThongTinHoSoFieldIndex.NguoiDungId, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NguoiDungId, value); }
		}

		/// <summary> The NguoiNopHoSo property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."nguoiNopHoSo"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String NguoiNopHoSo
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.NguoiNopHoSo, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.NguoiNopHoSo, value); }
		}

		/// <summary> The PhiDoVe property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."phiDoVe"<br/>
		/// Table field type characteristics (type, precision, scale, length): Float, 38, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Double> PhiDoVe
		{
			get { return (Nullable<System.Double>)GetValue((int)ThongTinHoSoFieldIndex.PhiDoVe, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.PhiDoVe, value); }
		}

		/// <summary> The PhiThamDinh property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."phiThamDinh"<br/>
		/// Table field type characteristics (type, precision, scale, length): Float, 38, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual Nullable<System.Double> PhiThamDinh
		{
			get { return (Nullable<System.Double>)GetValue((int)ThongTinHoSoFieldIndex.PhiThamDinh, false); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.PhiThamDinh, value); }
		}

		/// <summary> The SoBanVe property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soBanVe"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoBanVe
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoBanVe, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoBanVe, value); }
		}

		/// <summary> The SoBienNhan property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soBienNhan"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoBienNhan
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoBienNhan, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoBienNhan, value); }
		}

		/// <summary> The SoGiayTo property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soGiayTo"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoGiayTo
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoGiayTo, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoGiayTo, value); }
		}

		/// <summary> The SoGiayToNguoiNop property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soGiayToNguoiNop"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoGiayToNguoiNop
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoGiayToNguoiNop, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoGiayToNguoiNop, value); }
		}

		/// <summary> The SoHieuGiayChungNhan property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soHieuGiayChungNhan"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoHieuGiayChungNhan
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoHieuGiayChungNhan, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoHieuGiayChungNhan, value); }
		}

		/// <summary> The SoHieuToBanDo property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soHieuToBanDo"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoHieuToBanDo
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoHieuToBanDo, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoHieuToBanDo, value); }
		}

		/// <summary> The SoThuTuThua property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."soThuTuThua"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		
		public virtual System.String SoThuTuThua
		{
			get { return (System.String)GetValue((int)ThongTinHoSoFieldIndex.SoThuTuThua, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.SoThuTuThua, value); }
		}

		/// <summary> The ThongTinHoSoId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."thongTinHoSoId"<br/>
		/// Table field type characteristics (type, precision, scale, length): BigInt, 19, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		
		public virtual System.Int64 ThongTinHoSoId
		{
			get { return (System.Int64)GetValue((int)ThongTinHoSoFieldIndex.ThongTinHoSoId, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.ThongTinHoSoId, value); }
		}

		/// <summary> The XaId property of the Entity ThongTinHoSo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ThongTinHoSo"."xaId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		
		public virtual System.Int32 XaId
		{
			get { return (System.Int32)GetValue((int)ThongTinHoSoFieldIndex.XaId, true); }
			set	{ SetValue((int)ThongTinHoSoFieldIndex.XaId, value); }
		}

		/// <summary> Gets / sets related entity of type 'LoaiBienDongEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		
		[Browsable(false)]
		public virtual LoaiBienDongEntity LoaiBienDong
		{
			get	{ return _loaiBienDong; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncLoaiBienDong(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "ThongTinHoSos", "LoaiBienDong", _loaiBienDong, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'XaEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		
		[Browsable(false)]
		public virtual XaEntity Xa
		{
			get	{ return _xa; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncXa(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "ThongTinHoSos", "Xa", _xa, true); 
				}
			}
		}
	
		/// <summary> Gets the type of the hierarchy this entity is in. </summary>
		protected override InheritanceHierarchyType LLBLGenProIsInHierarchyOfType
		{
			get { return InheritanceHierarchyType.None;}
		}
		
		/// <summary> Gets or sets a value indicating whether this entity is a subtype</summary>
		protected override bool LLBLGenProIsSubType
		{
			get { return false;}
		}
		
		/// <summary>Returns the DAL.ManageDocument.EntityType enum value for this entity.</summary>
		[Browsable(false), XmlIgnore]
		protected override int LLBLGenProEntityTypeValue 
		{ 
			get { return (int)DAL.ManageDocument.EntityType.ThongTinHoSoEntity; }
		}

		#endregion


		#region Custom Entity code
		
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END
		
		#endregion

		#region Included code

		#endregion
	}
}
