//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using DAL.ManageDocument;
using DAL.ManageDocument.FactoryClasses;
using DAL.ManageDocument.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DAL.ManageDocument.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Huyen. </summary>
	public partial class HuyenRelations
	{
		/// <summary>CTor</summary>
		public HuyenRelations()
		{
		}

		/// <summary>Gets all relations of the HuyenEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.XaEntityUsingHuyenId);
			toReturn.Add(this.TinhEntityUsingTinhId);
			return toReturn;
		}

		#region Class Property Declarations

		/// <summary>Returns a new IEntityRelation object, between HuyenEntity and XaEntity over the 1:n relation they have, using the relation between the fields:
		/// Huyen.HuyenId - Xa.HuyenId
		/// </summary>
		public virtual IEntityRelation XaEntityUsingHuyenId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "Xas" , true);
				relation.AddEntityFieldPair(HuyenFields.HuyenId, XaFields.HuyenId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("HuyenEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("XaEntity", false);
				return relation;
			}
		}


		/// <summary>Returns a new IEntityRelation object, between HuyenEntity and TinhEntity over the m:1 relation they have, using the relation between the fields:
		/// Huyen.TinhId - Tinh.TinhId
		/// </summary>
		public virtual IEntityRelation TinhEntityUsingTinhId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Tinh", false);
				relation.AddEntityFieldPair(TinhFields.TinhId, HuyenFields.TinhId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("TinhEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("HuyenEntity", true);
				return relation;
			}
		}
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticHuyenRelations
	{
		internal static readonly IEntityRelation XaEntityUsingHuyenIdStatic = new HuyenRelations().XaEntityUsingHuyenId;
		internal static readonly IEntityRelation TinhEntityUsingTinhIdStatic = new HuyenRelations().TinhEntityUsingTinhId;

		/// <summary>CTor</summary>
		static StaticHuyenRelations()
		{
		}
	}
}
