//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using DAL.ManageDocument;
using DAL.ManageDocument.FactoryClasses;
using DAL.ManageDocument.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DAL.ManageDocument.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ThongTinHoSo. </summary>
	public partial class ThongTinHoSoRelations
	{
		/// <summary>CTor</summary>
		public ThongTinHoSoRelations()
		{
		}

		/// <summary>Gets all relations of the ThongTinHoSoEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.LoaiBienDongEntityUsingLoaiBienDongId);
			toReturn.Add(this.XaEntityUsingXaId);
			return toReturn;
		}

		#region Class Property Declarations



		/// <summary>Returns a new IEntityRelation object, between ThongTinHoSoEntity and LoaiBienDongEntity over the m:1 relation they have, using the relation between the fields:
		/// ThongTinHoSo.LoaiBienDongId - LoaiBienDong.LoaiBienDongId
		/// </summary>
		public virtual IEntityRelation LoaiBienDongEntityUsingLoaiBienDongId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "LoaiBienDong", false);
				relation.AddEntityFieldPair(LoaiBienDongFields.LoaiBienDongId, ThongTinHoSoFields.LoaiBienDongId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("LoaiBienDongEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ThongTinHoSoEntity", true);
				return relation;
			}
		}
		/// <summary>Returns a new IEntityRelation object, between ThongTinHoSoEntity and XaEntity over the m:1 relation they have, using the relation between the fields:
		/// ThongTinHoSo.XaId - Xa.XaId
		/// </summary>
		public virtual IEntityRelation XaEntityUsingXaId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Xa", false);
				relation.AddEntityFieldPair(XaFields.XaId, ThongTinHoSoFields.XaId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("XaEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ThongTinHoSoEntity", true);
				return relation;
			}
		}
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticThongTinHoSoRelations
	{
		internal static readonly IEntityRelation LoaiBienDongEntityUsingLoaiBienDongIdStatic = new ThongTinHoSoRelations().LoaiBienDongEntityUsingLoaiBienDongId;
		internal static readonly IEntityRelation XaEntityUsingXaIdStatic = new ThongTinHoSoRelations().XaEntityUsingXaId;

		/// <summary>CTor</summary>
		static StaticThongTinHoSoRelations()
		{
		}
	}
}
