//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Data;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DAL.ManageDocument.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	/// <remarks>It uses a single instance of an internal class. The access isn't marked with locks as the PersistenceInfoProviderBase class is threadsafe.</remarks>
	internal static class PersistenceInfoProviderSingleton
	{
		#region Class Member Declarations
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();
		#endregion

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton()
		{
		}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCauHinhEntityMappings();
			InitChuyenVienEntityMappings();
			InitCongTyDoVeEntityMappings();
			InitHuyenEntityMappings();
			InitLoaiBienDongEntityMappings();
			InitLoaiGiayToEntityMappings();
			InitNguoiDungEntityMappings();
			InitThongTinHoSoEntityMappings();
			InitTinhEntityMappings();
			InitXaEntityMappings();
		}

		/// <summary>Inits CauHinhEntity's mappings</summary>
		private void InitCauHinhEntityMappings()
		{
			this.AddElementMapping("CauHinhEntity", @"MTD", @"dbo", "CauHinh", 4, 0);
			this.AddElementFieldMapping("CauHinhEntity", "CauHinhId", "cauHinhId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("CauHinhEntity", "GiaTri", "giaTri", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("CauHinhEntity", "NguoiDungId", "nguoiDungId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("CauHinhEntity", "TenCauHinh", "tenCauHinh", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits ChuyenVienEntity's mappings</summary>
		private void InitChuyenVienEntityMappings()
		{
			this.AddElementMapping("ChuyenVienEntity", @"MTD", @"dbo", "ChuyenVien", 2, 0);
			this.AddElementFieldMapping("ChuyenVienEntity", "ChuyenVienId", "chuyenVienId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("ChuyenVienEntity", "TenChuyenVien", "tenChuyenVien", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits CongTyDoVeEntity's mappings</summary>
		private void InitCongTyDoVeEntityMappings()
		{
			this.AddElementMapping("CongTyDoVeEntity", @"MTD", @"dbo", "CongTyDoVe", 2, 0);
			this.AddElementFieldMapping("CongTyDoVeEntity", "CongTyDoVeId", "congTyDoVeId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("CongTyDoVeEntity", "TenCongTyDoVe", "tenCongTyDoVe", true, "NVarChar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits HuyenEntity's mappings</summary>
		private void InitHuyenEntityMappings()
		{
			this.AddElementMapping("HuyenEntity", @"MTD", @"dbo", "Huyen", 4, 0);
			this.AddElementFieldMapping("HuyenEntity", "HuyenId", "huyenId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("HuyenEntity", "Mahuyen", "mahuyen", false, "NVarChar", 3, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("HuyenEntity", "TenHuyen", "tenHuyen", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("HuyenEntity", "TinhId", "tinhId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits LoaiBienDongEntity's mappings</summary>
		private void InitLoaiBienDongEntityMappings()
		{
			this.AddElementMapping("LoaiBienDongEntity", @"MTD", @"dbo", "LoaiBienDong", 3, 0);
			this.AddElementFieldMapping("LoaiBienDongEntity", "LoaiBienDongId", "loaiBienDongId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("LoaiBienDongEntity", "MaLoaiBienDong", "maLoaiBienDong", true, "NVarChar", 10, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("LoaiBienDongEntity", "TenLoaiBienDong", "tenLoaiBienDong", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits LoaiGiayToEntity's mappings</summary>
		private void InitLoaiGiayToEntityMappings()
		{
			this.AddElementMapping("LoaiGiayToEntity", @"MTD", @"dbo", "LoaiGiayTo", 4, 0);
			this.AddElementFieldMapping("LoaiGiayToEntity", "LoaiGiayToId", "loaiGiayToId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("LoaiGiayToEntity", "MaLoaiGiayTo", "maLoaiGiayTo", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("LoaiGiayToEntity", "TenLoaiGiayTo", "tenLoaiGiayTo", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("LoaiGiayToEntity", "TypeIndex", "typeIndex", true, "TinyInt", 0, 3, 0, false, "", null, typeof(System.Byte), 3);
		}

		/// <summary>Inits NguoiDungEntity's mappings</summary>
		private void InitNguoiDungEntityMappings()
		{
			this.AddElementMapping("NguoiDungEntity", @"MTD", @"dbo", "NguoiDung", 8, 0);
			this.AddElementFieldMapping("NguoiDungEntity", "DiaChiEmail", "diaChiEmail", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("NguoiDungEntity", "GioiTinh", "gioiTinh", false, "TinyInt", 0, 3, 0, false, "", null, typeof(System.Byte), 1);
			this.AddElementFieldMapping("NguoiDungEntity", "HoTenNguoiDung", "hoTenNguoiDung", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("NguoiDungEntity", "MatKhau", "matKhau", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("NguoiDungEntity", "NguoiDungId", "nguoiDungId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("NguoiDungEntity", "SoDienThoai", "soDienThoai", true, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("NguoiDungEntity", "TenDangNhap", "tenDangNhap", false, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("NguoiDungEntity", "VaiTro", "vaiTro", false, "TinyInt", 0, 3, 0, false, "", null, typeof(System.Byte), 7);
		}

		/// <summary>Inits ThongTinHoSoEntity's mappings</summary>
		private void InitThongTinHoSoEntityMappings()
		{
			this.AddElementMapping("ThongTinHoSoEntity", @"MTD", @"dbo", "ThongTinHoSo", 34, 0);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "ChiTietHoSo", "chiTietHoSo", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "ChuyenVienId", "chuyenVienId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "ChuyenVienKiemTra", "chuyenVienKiemTra", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "CongTyDoVe", "congTyDoVe", true, "NVarChar", 1000, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "CongTyDoVeId", "congTyDoVeId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "GhiChu", "ghiChu", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "GioiTinhNguoiNop", "gioiTinhNguoiNop", true, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 6);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "HoSoChuaDat", "hoSoChuaDat", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 7);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "HoSoDaKiemTra", "hoSoDaKiemTra", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 8);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "HoSoKhongHopLy", "hoSoKhongHopLy", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 9);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "HoSoMoiNhat", "hoSoMoiNhat", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 10);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "HoTen", "hoTen", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "KhoaChaId", "khoaChaId", true, "BigInt", 0, 19, 0, false, "", null, typeof(System.Int64), 12);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "LichSuCapNhat", "lichSuCapNhat", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "LoaiBienDongId", "loaiBienDongId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 14);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NgayChinhSua", "ngayChinhSua", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 15);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NgayHenTra", "ngayHenTra", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 16);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NgayKiemTraNoiNghiep", "ngayKiemTraNoiNghiep", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 17);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NgayNop", "ngayNop", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 18);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NgayTraHoSo", "ngayTraHoSo", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 19);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NguoiDungId", "nguoiDungId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 20);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "NguoiNopHoSo", "nguoiNopHoSo", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 21);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "PhiDoVe", "phiDoVe", true, "Float", 0, 38, 0, false, "", null, typeof(System.Double), 22);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "PhiThamDinh", "phiThamDinh", true, "Float", 0, 38, 0, false, "", null, typeof(System.Double), 23);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "RootId", "rootId", false, "BigInt", 0, 19, 0, false, "", null, typeof(System.Int64), 24);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoBanVe", "soBanVe", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 25);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoBienNhan", "soBienNhan", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 26);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoGiayTo", "soGiayTo", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 27);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoGiayToNguoiNop", "soGiayToNguoiNop", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 28);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoHieuGiayChungNhan", "soHieuGiayChungNhan", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 29);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoHieuToBanDo", "soHieuToBanDo", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 30);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "SoThuTuThua", "soThuTuThua", true, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 31);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "ThongTinHoSoId", "thongTinHoSoId", false, "BigInt", 0, 19, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int64), 32);
			this.AddElementFieldMapping("ThongTinHoSoEntity", "XaId", "xaId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 33);
		}

		/// <summary>Inits TinhEntity's mappings</summary>
		private void InitTinhEntityMappings()
		{
			this.AddElementMapping("TinhEntity", @"MTD", @"dbo", "Tinh", 3, 0);
			this.AddElementFieldMapping("TinhEntity", "MaTinh", "maTinh", false, "NVarChar", 2, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("TinhEntity", "TenTinh", "tenTinh", false, "NVarChar", 30, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("TinhEntity", "TinhId", "tinhId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
		}

		/// <summary>Inits XaEntity's mappings</summary>
		private void InitXaEntityMappings()
		{
			this.AddElementMapping("XaEntity", @"MTD", @"dbo", "Xa", 4, 0);
			this.AddElementFieldMapping("XaEntity", "HuyenId", "huyenId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("XaEntity", "MaXa", "maXa", false, "NVarChar", 5, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("XaEntity", "TenXa", "tenXa", false, "NVarChar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("XaEntity", "XaId", "xaId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

	}
}
