//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DAL.ManageDocument.HelperClasses
{
	
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	
	
	/// <summary>Singleton implementation of the FieldInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	/// <remarks>It uses a single instance of an internal class. The access isn't marked with locks as the FieldInfoProviderBase class is threadsafe.</remarks>
	internal static class FieldInfoProviderSingleton
	{
		#region Class Member Declarations
		private static readonly IFieldInfoProvider _providerInstance = new FieldInfoProviderCore();
		#endregion

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static FieldInfoProviderSingleton()
		{
		}

		/// <summary>Gets the singleton instance of the FieldInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IFieldInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the FieldInfoProvider. Used by singleton wrapper.</summary>
	internal class FieldInfoProviderCore : FieldInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="FieldInfoProviderCore"/> class.</summary>
		internal FieldInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCauHinhEntityInfos();
			InitChuyenVienEntityInfos();
			InitCongTyDoVeEntityInfos();
			InitHuyenEntityInfos();
			InitLoaiBienDongEntityInfos();
			InitLoaiGiayToEntityInfos();
			InitNguoiDungEntityInfos();
			InitThongTinHoSoEntityInfos();
			InitTinhEntityInfos();
			InitXaEntityInfos();

			this.ConstructElementFieldStructures(InheritanceInfoProviderSingleton.GetInstance());
		}

		/// <summary>Inits CauHinhEntity's FieldInfo objects</summary>
		private void InitCauHinhEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(CauHinhFieldIndex), "CauHinhEntity");
			this.AddElementFieldInfo("CauHinhEntity", "CauHinhId", typeof(System.Int32), true, false, true, false,  (int)CauHinhFieldIndex.CauHinhId, 0, 0, 10);
			this.AddElementFieldInfo("CauHinhEntity", "GiaTri", typeof(System.String), false, false, false, true,  (int)CauHinhFieldIndex.GiaTri, 2147483647, 0, 0);
			this.AddElementFieldInfo("CauHinhEntity", "NguoiDungId", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CauHinhFieldIndex.NguoiDungId, 0, 0, 10);
			this.AddElementFieldInfo("CauHinhEntity", "TenCauHinh", typeof(System.String), false, false, false, true,  (int)CauHinhFieldIndex.TenCauHinh, 255, 0, 0);
		}
		/// <summary>Inits ChuyenVienEntity's FieldInfo objects</summary>
		private void InitChuyenVienEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(ChuyenVienFieldIndex), "ChuyenVienEntity");
			this.AddElementFieldInfo("ChuyenVienEntity", "ChuyenVienId", typeof(System.Int32), true, false, true, false,  (int)ChuyenVienFieldIndex.ChuyenVienId, 0, 0, 10);
			this.AddElementFieldInfo("ChuyenVienEntity", "TenChuyenVien", typeof(System.String), false, false, false, true,  (int)ChuyenVienFieldIndex.TenChuyenVien, 255, 0, 0);
		}
		/// <summary>Inits CongTyDoVeEntity's FieldInfo objects</summary>
		private void InitCongTyDoVeEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(CongTyDoVeFieldIndex), "CongTyDoVeEntity");
			this.AddElementFieldInfo("CongTyDoVeEntity", "CongTyDoVeId", typeof(System.Int32), true, false, true, false,  (int)CongTyDoVeFieldIndex.CongTyDoVeId, 0, 0, 10);
			this.AddElementFieldInfo("CongTyDoVeEntity", "TenCongTyDoVe", typeof(System.String), false, false, false, true,  (int)CongTyDoVeFieldIndex.TenCongTyDoVe, 1000, 0, 0);
		}
		/// <summary>Inits HuyenEntity's FieldInfo objects</summary>
		private void InitHuyenEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(HuyenFieldIndex), "HuyenEntity");
			this.AddElementFieldInfo("HuyenEntity", "HuyenId", typeof(System.Int32), true, false, false, false,  (int)HuyenFieldIndex.HuyenId, 0, 0, 10);
			this.AddElementFieldInfo("HuyenEntity", "Mahuyen", typeof(System.String), false, false, false, false,  (int)HuyenFieldIndex.Mahuyen, 3, 0, 0);
			this.AddElementFieldInfo("HuyenEntity", "TenHuyen", typeof(System.String), false, false, false, false,  (int)HuyenFieldIndex.TenHuyen, 255, 0, 0);
			this.AddElementFieldInfo("HuyenEntity", "TinhId", typeof(System.Int32), false, true, false, false,  (int)HuyenFieldIndex.TinhId, 0, 0, 10);
		}
		/// <summary>Inits LoaiBienDongEntity's FieldInfo objects</summary>
		private void InitLoaiBienDongEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(LoaiBienDongFieldIndex), "LoaiBienDongEntity");
			this.AddElementFieldInfo("LoaiBienDongEntity", "LoaiBienDongId", typeof(System.Int32), true, false, true, false,  (int)LoaiBienDongFieldIndex.LoaiBienDongId, 0, 0, 10);
			this.AddElementFieldInfo("LoaiBienDongEntity", "MaLoaiBienDong", typeof(System.String), false, false, false, true,  (int)LoaiBienDongFieldIndex.MaLoaiBienDong, 10, 0, 0);
			this.AddElementFieldInfo("LoaiBienDongEntity", "TenLoaiBienDong", typeof(System.String), false, false, false, true,  (int)LoaiBienDongFieldIndex.TenLoaiBienDong, 255, 0, 0);
		}
		/// <summary>Inits LoaiGiayToEntity's FieldInfo objects</summary>
		private void InitLoaiGiayToEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(LoaiGiayToFieldIndex), "LoaiGiayToEntity");
			this.AddElementFieldInfo("LoaiGiayToEntity", "LoaiGiayToId", typeof(System.Int32), true, false, true, false,  (int)LoaiGiayToFieldIndex.LoaiGiayToId, 0, 0, 10);
			this.AddElementFieldInfo("LoaiGiayToEntity", "MaLoaiGiayTo", typeof(System.String), false, false, false, true,  (int)LoaiGiayToFieldIndex.MaLoaiGiayTo, 50, 0, 0);
			this.AddElementFieldInfo("LoaiGiayToEntity", "TenLoaiGiayTo", typeof(System.String), false, false, false, true,  (int)LoaiGiayToFieldIndex.TenLoaiGiayTo, 255, 0, 0);
			this.AddElementFieldInfo("LoaiGiayToEntity", "TypeIndex", typeof(Nullable<System.Byte>), false, false, false, true,  (int)LoaiGiayToFieldIndex.TypeIndex, 0, 0, 3);
		}
		/// <summary>Inits NguoiDungEntity's FieldInfo objects</summary>
		private void InitNguoiDungEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(NguoiDungFieldIndex), "NguoiDungEntity");
			this.AddElementFieldInfo("NguoiDungEntity", "DiaChiEmail", typeof(System.String), false, false, false, true,  (int)NguoiDungFieldIndex.DiaChiEmail, 100, 0, 0);
			this.AddElementFieldInfo("NguoiDungEntity", "GioiTinh", typeof(System.Byte), false, false, false, false,  (int)NguoiDungFieldIndex.GioiTinh, 0, 0, 3);
			this.AddElementFieldInfo("NguoiDungEntity", "HoTenNguoiDung", typeof(System.String), false, false, false, true,  (int)NguoiDungFieldIndex.HoTenNguoiDung, 100, 0, 0);
			this.AddElementFieldInfo("NguoiDungEntity", "MatKhau", typeof(System.String), false, false, false, true,  (int)NguoiDungFieldIndex.MatKhau, 100, 0, 0);
			this.AddElementFieldInfo("NguoiDungEntity", "NguoiDungId", typeof(System.Int32), true, false, true, false,  (int)NguoiDungFieldIndex.NguoiDungId, 0, 0, 10);
			this.AddElementFieldInfo("NguoiDungEntity", "SoDienThoai", typeof(System.String), false, false, false, true,  (int)NguoiDungFieldIndex.SoDienThoai, 20, 0, 0);
			this.AddElementFieldInfo("NguoiDungEntity", "TenDangNhap", typeof(System.String), false, false, false, false,  (int)NguoiDungFieldIndex.TenDangNhap, 50, 0, 0);
			this.AddElementFieldInfo("NguoiDungEntity", "VaiTro", typeof(System.Byte), false, false, false, false,  (int)NguoiDungFieldIndex.VaiTro, 0, 0, 3);
		}
		/// <summary>Inits ThongTinHoSoEntity's FieldInfo objects</summary>
		private void InitThongTinHoSoEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(ThongTinHoSoFieldIndex), "ThongTinHoSoEntity");
			this.AddElementFieldInfo("ThongTinHoSoEntity", "ChiTietHoSo", typeof(System.String), false, false, false, false,  (int)ThongTinHoSoFieldIndex.ChiTietHoSo, 2147483647, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "ChuyenVienId", typeof(Nullable<System.Int32>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.ChuyenVienId, 0, 0, 10);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "ChuyenVienKiemTra", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.ChuyenVienKiemTra, 255, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "CongTyDoVe", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.CongTyDoVe, 1000, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "CongTyDoVeId", typeof(Nullable<System.Int32>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.CongTyDoVeId, 0, 0, 10);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "GhiChu", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.GhiChu, 2147483647, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "GioiTinhNguoiNop", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.GioiTinhNguoiNop, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "HoSoMoiNhat", typeof(System.Boolean), false, false, false, false,  (int)ThongTinHoSoFieldIndex.HoSoMoiNhat, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "HoTen", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.HoTen, 2147483647, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "KhoaChaId", typeof(Nullable<System.Int64>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.KhoaChaId, 0, 0, 19);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "LichSuCapNhat", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.LichSuCapNhat, 2147483647, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "LoaiBienDongId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ThongTinHoSoFieldIndex.LoaiBienDongId, 0, 0, 10);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NgayChinhSua", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NgayChinhSua, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NgayHenTra", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NgayHenTra, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NgayKiemTraNoiNghiep", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NgayKiemTraNoiNghiep, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NgayNop", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NgayNop, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NgayTraHoSo", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NgayTraHoSo, 0, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NguoiDungId", typeof(Nullable<System.Int32>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NguoiDungId, 0, 0, 10);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "NguoiNopHoSo", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.NguoiNopHoSo, 255, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "PhiDoVe", typeof(Nullable<System.Double>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.PhiDoVe, 0, 0, 38);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "PhiThamDinh", typeof(Nullable<System.Double>), false, false, false, true,  (int)ThongTinHoSoFieldIndex.PhiThamDinh, 0, 0, 38);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoBanVe", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoBanVe, 50, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoBienNhan", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoBienNhan, 50, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoGiayTo", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoGiayTo, 2147483647, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoGiayToNguoiNop", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoGiayToNguoiNop, 50, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoHieuGiayChungNhan", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoHieuGiayChungNhan, 2147483647, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoHieuToBanDo", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoHieuToBanDo, 255, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "SoThuTuThua", typeof(System.String), false, false, false, true,  (int)ThongTinHoSoFieldIndex.SoThuTuThua, 255, 0, 0);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "ThongTinHoSoId", typeof(System.Int64), true, false, true, false,  (int)ThongTinHoSoFieldIndex.ThongTinHoSoId, 0, 0, 19);
			this.AddElementFieldInfo("ThongTinHoSoEntity", "XaId", typeof(System.Int32), false, true, false, false,  (int)ThongTinHoSoFieldIndex.XaId, 0, 0, 10);
		}
		/// <summary>Inits TinhEntity's FieldInfo objects</summary>
		private void InitTinhEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(TinhFieldIndex), "TinhEntity");
			this.AddElementFieldInfo("TinhEntity", "MaTinh", typeof(System.String), false, false, false, false,  (int)TinhFieldIndex.MaTinh, 2, 0, 0);
			this.AddElementFieldInfo("TinhEntity", "TenTinh", typeof(System.String), false, false, false, false,  (int)TinhFieldIndex.TenTinh, 30, 0, 0);
			this.AddElementFieldInfo("TinhEntity", "TinhId", typeof(System.Int32), true, false, false, false,  (int)TinhFieldIndex.TinhId, 0, 0, 10);
		}
		/// <summary>Inits XaEntity's FieldInfo objects</summary>
		private void InitXaEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(XaFieldIndex), "XaEntity");
			this.AddElementFieldInfo("XaEntity", "HuyenId", typeof(System.Int32), false, true, false, false,  (int)XaFieldIndex.HuyenId, 0, 0, 10);
			this.AddElementFieldInfo("XaEntity", "MaXa", typeof(System.String), false, false, false, false,  (int)XaFieldIndex.MaXa, 5, 0, 0);
			this.AddElementFieldInfo("XaEntity", "TenXa", typeof(System.String), false, false, false, false,  (int)XaFieldIndex.TenXa, 255, 0, 0);
			this.AddElementFieldInfo("XaEntity", "XaId", typeof(System.Int32), true, false, false, false,  (int)XaFieldIndex.XaId, 0, 0, 10);
		}
		
	}
}




