//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;
using DAL.ManageDocument.FactoryClasses;
using DAL.ManageDocument;

namespace DAL.ManageDocument.HelperClasses
{
	/// <summary>Field Creation Class for entity CauHinhEntity</summary>
	public partial class CauHinhFields
	{
		/// <summary>Creates a new CauHinhEntity.CauHinhId field instance</summary>
		public static EntityField2 CauHinhId
		{
			get { return (EntityField2)EntityFieldFactory.Create(CauHinhFieldIndex.CauHinhId);}
		}
		/// <summary>Creates a new CauHinhEntity.GiaTri field instance</summary>
		public static EntityField2 GiaTri
		{
			get { return (EntityField2)EntityFieldFactory.Create(CauHinhFieldIndex.GiaTri);}
		}
		/// <summary>Creates a new CauHinhEntity.NguoiDungId field instance</summary>
		public static EntityField2 NguoiDungId
		{
			get { return (EntityField2)EntityFieldFactory.Create(CauHinhFieldIndex.NguoiDungId);}
		}
		/// <summary>Creates a new CauHinhEntity.TenCauHinh field instance</summary>
		public static EntityField2 TenCauHinh
		{
			get { return (EntityField2)EntityFieldFactory.Create(CauHinhFieldIndex.TenCauHinh);}
		}
	}

	/// <summary>Field Creation Class for entity ChuyenVienEntity</summary>
	public partial class ChuyenVienFields
	{
		/// <summary>Creates a new ChuyenVienEntity.ChuyenVienId field instance</summary>
		public static EntityField2 ChuyenVienId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ChuyenVienFieldIndex.ChuyenVienId);}
		}
		/// <summary>Creates a new ChuyenVienEntity.TenChuyenVien field instance</summary>
		public static EntityField2 TenChuyenVien
		{
			get { return (EntityField2)EntityFieldFactory.Create(ChuyenVienFieldIndex.TenChuyenVien);}
		}
	}

	/// <summary>Field Creation Class for entity CongTyDoVeEntity</summary>
	public partial class CongTyDoVeFields
	{
		/// <summary>Creates a new CongTyDoVeEntity.CongTyDoVeId field instance</summary>
		public static EntityField2 CongTyDoVeId
		{
			get { return (EntityField2)EntityFieldFactory.Create(CongTyDoVeFieldIndex.CongTyDoVeId);}
		}
		/// <summary>Creates a new CongTyDoVeEntity.TenCongTyDoVe field instance</summary>
		public static EntityField2 TenCongTyDoVe
		{
			get { return (EntityField2)EntityFieldFactory.Create(CongTyDoVeFieldIndex.TenCongTyDoVe);}
		}
	}

	/// <summary>Field Creation Class for entity HuyenEntity</summary>
	public partial class HuyenFields
	{
		/// <summary>Creates a new HuyenEntity.HuyenId field instance</summary>
		public static EntityField2 HuyenId
		{
			get { return (EntityField2)EntityFieldFactory.Create(HuyenFieldIndex.HuyenId);}
		}
		/// <summary>Creates a new HuyenEntity.Mahuyen field instance</summary>
		public static EntityField2 Mahuyen
		{
			get { return (EntityField2)EntityFieldFactory.Create(HuyenFieldIndex.Mahuyen);}
		}
		/// <summary>Creates a new HuyenEntity.TenHuyen field instance</summary>
		public static EntityField2 TenHuyen
		{
			get { return (EntityField2)EntityFieldFactory.Create(HuyenFieldIndex.TenHuyen);}
		}
		/// <summary>Creates a new HuyenEntity.TinhId field instance</summary>
		public static EntityField2 TinhId
		{
			get { return (EntityField2)EntityFieldFactory.Create(HuyenFieldIndex.TinhId);}
		}
	}

	/// <summary>Field Creation Class for entity LoaiBienDongEntity</summary>
	public partial class LoaiBienDongFields
	{
		/// <summary>Creates a new LoaiBienDongEntity.LoaiBienDongId field instance</summary>
		public static EntityField2 LoaiBienDongId
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiBienDongFieldIndex.LoaiBienDongId);}
		}
		/// <summary>Creates a new LoaiBienDongEntity.MaLoaiBienDong field instance</summary>
		public static EntityField2 MaLoaiBienDong
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiBienDongFieldIndex.MaLoaiBienDong);}
		}
		/// <summary>Creates a new LoaiBienDongEntity.TenLoaiBienDong field instance</summary>
		public static EntityField2 TenLoaiBienDong
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiBienDongFieldIndex.TenLoaiBienDong);}
		}
	}

	/// <summary>Field Creation Class for entity LoaiGiayToEntity</summary>
	public partial class LoaiGiayToFields
	{
		/// <summary>Creates a new LoaiGiayToEntity.LoaiGiayToId field instance</summary>
		public static EntityField2 LoaiGiayToId
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiGiayToFieldIndex.LoaiGiayToId);}
		}
		/// <summary>Creates a new LoaiGiayToEntity.MaLoaiGiayTo field instance</summary>
		public static EntityField2 MaLoaiGiayTo
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiGiayToFieldIndex.MaLoaiGiayTo);}
		}
		/// <summary>Creates a new LoaiGiayToEntity.TenLoaiGiayTo field instance</summary>
		public static EntityField2 TenLoaiGiayTo
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiGiayToFieldIndex.TenLoaiGiayTo);}
		}
		/// <summary>Creates a new LoaiGiayToEntity.TypeIndex field instance</summary>
		public static EntityField2 TypeIndex
		{
			get { return (EntityField2)EntityFieldFactory.Create(LoaiGiayToFieldIndex.TypeIndex);}
		}
	}

	/// <summary>Field Creation Class for entity NguoiDungEntity</summary>
	public partial class NguoiDungFields
	{
		/// <summary>Creates a new NguoiDungEntity.DiaChiEmail field instance</summary>
		public static EntityField2 DiaChiEmail
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.DiaChiEmail);}
		}
		/// <summary>Creates a new NguoiDungEntity.GioiTinh field instance</summary>
		public static EntityField2 GioiTinh
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.GioiTinh);}
		}
		/// <summary>Creates a new NguoiDungEntity.HoTenNguoiDung field instance</summary>
		public static EntityField2 HoTenNguoiDung
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.HoTenNguoiDung);}
		}
		/// <summary>Creates a new NguoiDungEntity.MatKhau field instance</summary>
		public static EntityField2 MatKhau
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.MatKhau);}
		}
		/// <summary>Creates a new NguoiDungEntity.NguoiDungId field instance</summary>
		public static EntityField2 NguoiDungId
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.NguoiDungId);}
		}
		/// <summary>Creates a new NguoiDungEntity.SoDienThoai field instance</summary>
		public static EntityField2 SoDienThoai
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.SoDienThoai);}
		}
		/// <summary>Creates a new NguoiDungEntity.TenDangNhap field instance</summary>
		public static EntityField2 TenDangNhap
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.TenDangNhap);}
		}
		/// <summary>Creates a new NguoiDungEntity.VaiTro field instance</summary>
		public static EntityField2 VaiTro
		{
			get { return (EntityField2)EntityFieldFactory.Create(NguoiDungFieldIndex.VaiTro);}
		}
	}

	/// <summary>Field Creation Class for entity ThongTinHoSoEntity</summary>
	public partial class ThongTinHoSoFields
	{
		/// <summary>Creates a new ThongTinHoSoEntity.ChiTietHoSo field instance</summary>
		public static EntityField2 ChiTietHoSo
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.ChiTietHoSo);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.ChuyenVienId field instance</summary>
		public static EntityField2 ChuyenVienId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.ChuyenVienId);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.ChuyenVienKiemTra field instance</summary>
		public static EntityField2 ChuyenVienKiemTra
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.ChuyenVienKiemTra);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.CongTyDoVe field instance</summary>
		public static EntityField2 CongTyDoVe
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.CongTyDoVe);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.CongTyDoVeId field instance</summary>
		public static EntityField2 CongTyDoVeId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.CongTyDoVeId);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.GhiChu field instance</summary>
		public static EntityField2 GhiChu
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.GhiChu);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.GioiTinhNguoiNop field instance</summary>
		public static EntityField2 GioiTinhNguoiNop
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.GioiTinhNguoiNop);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.HoSoMoiNhat field instance</summary>
		public static EntityField2 HoSoMoiNhat
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.HoSoMoiNhat);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.HoTen field instance</summary>
		public static EntityField2 HoTen
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.HoTen);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.KhoaChaId field instance</summary>
		public static EntityField2 KhoaChaId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.KhoaChaId);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.LichSuCapNhat field instance</summary>
		public static EntityField2 LichSuCapNhat
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.LichSuCapNhat);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.LoaiBienDongId field instance</summary>
		public static EntityField2 LoaiBienDongId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.LoaiBienDongId);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NgayChinhSua field instance</summary>
		public static EntityField2 NgayChinhSua
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NgayChinhSua);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NgayHenTra field instance</summary>
		public static EntityField2 NgayHenTra
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NgayHenTra);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NgayKiemTraNoiNghiep field instance</summary>
		public static EntityField2 NgayKiemTraNoiNghiep
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NgayKiemTraNoiNghiep);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NgayNop field instance</summary>
		public static EntityField2 NgayNop
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NgayNop);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NgayTraHoSo field instance</summary>
		public static EntityField2 NgayTraHoSo
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NgayTraHoSo);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NguoiDungId field instance</summary>
		public static EntityField2 NguoiDungId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NguoiDungId);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.NguoiNopHoSo field instance</summary>
		public static EntityField2 NguoiNopHoSo
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.NguoiNopHoSo);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.PhiDoVe field instance</summary>
		public static EntityField2 PhiDoVe
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.PhiDoVe);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.PhiThamDinh field instance</summary>
		public static EntityField2 PhiThamDinh
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.PhiThamDinh);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoBanVe field instance</summary>
		public static EntityField2 SoBanVe
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoBanVe);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoBienNhan field instance</summary>
		public static EntityField2 SoBienNhan
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoBienNhan);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoGiayTo field instance</summary>
		public static EntityField2 SoGiayTo
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoGiayTo);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoGiayToNguoiNop field instance</summary>
		public static EntityField2 SoGiayToNguoiNop
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoGiayToNguoiNop);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoHieuGiayChungNhan field instance</summary>
		public static EntityField2 SoHieuGiayChungNhan
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoHieuGiayChungNhan);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoHieuToBanDo field instance</summary>
		public static EntityField2 SoHieuToBanDo
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoHieuToBanDo);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.SoThuTuThua field instance</summary>
		public static EntityField2 SoThuTuThua
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.SoThuTuThua);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.ThongTinHoSoId field instance</summary>
		public static EntityField2 ThongTinHoSoId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.ThongTinHoSoId);}
		}
		/// <summary>Creates a new ThongTinHoSoEntity.XaId field instance</summary>
		public static EntityField2 XaId
		{
			get { return (EntityField2)EntityFieldFactory.Create(ThongTinHoSoFieldIndex.XaId);}
		}
	}

	/// <summary>Field Creation Class for entity TinhEntity</summary>
	public partial class TinhFields
	{
		/// <summary>Creates a new TinhEntity.MaTinh field instance</summary>
		public static EntityField2 MaTinh
		{
			get { return (EntityField2)EntityFieldFactory.Create(TinhFieldIndex.MaTinh);}
		}
		/// <summary>Creates a new TinhEntity.TenTinh field instance</summary>
		public static EntityField2 TenTinh
		{
			get { return (EntityField2)EntityFieldFactory.Create(TinhFieldIndex.TenTinh);}
		}
		/// <summary>Creates a new TinhEntity.TinhId field instance</summary>
		public static EntityField2 TinhId
		{
			get { return (EntityField2)EntityFieldFactory.Create(TinhFieldIndex.TinhId);}
		}
	}

	/// <summary>Field Creation Class for entity XaEntity</summary>
	public partial class XaFields
	{
		/// <summary>Creates a new XaEntity.HuyenId field instance</summary>
		public static EntityField2 HuyenId
		{
			get { return (EntityField2)EntityFieldFactory.Create(XaFieldIndex.HuyenId);}
		}
		/// <summary>Creates a new XaEntity.MaXa field instance</summary>
		public static EntityField2 MaXa
		{
			get { return (EntityField2)EntityFieldFactory.Create(XaFieldIndex.MaXa);}
		}
		/// <summary>Creates a new XaEntity.TenXa field instance</summary>
		public static EntityField2 TenXa
		{
			get { return (EntityField2)EntityFieldFactory.Create(XaFieldIndex.TenXa);}
		}
		/// <summary>Creates a new XaEntity.XaId field instance</summary>
		public static EntityField2 XaId
		{
			get { return (EntityField2)EntityFieldFactory.Create(XaFieldIndex.XaId);}
		}
	}
	

}