//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;

namespace DAL.ManageDocument
{
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: CauHinh.</summary>
	public enum CauHinhFieldIndex
	{
		///<summary>CauHinhId. </summary>
		CauHinhId,
		///<summary>GiaTri. </summary>
		GiaTri,
		///<summary>NguoiDungId. </summary>
		NguoiDungId,
		///<summary>TenCauHinh. </summary>
		TenCauHinh,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: ChuyenVien.</summary>
	public enum ChuyenVienFieldIndex
	{
		///<summary>ChuyenVienId. </summary>
		ChuyenVienId,
		///<summary>TenChuyenVien. </summary>
		TenChuyenVien,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: CongTyDoVe.</summary>
	public enum CongTyDoVeFieldIndex
	{
		///<summary>CongTyDoVeId. </summary>
		CongTyDoVeId,
		///<summary>TenCongTyDoVe. </summary>
		TenCongTyDoVe,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Huyen.</summary>
	public enum HuyenFieldIndex
	{
		///<summary>HuyenId. </summary>
		HuyenId,
		///<summary>Mahuyen. </summary>
		Mahuyen,
		///<summary>TenHuyen. </summary>
		TenHuyen,
		///<summary>TinhId. </summary>
		TinhId,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: LoaiBienDong.</summary>
	public enum LoaiBienDongFieldIndex
	{
		///<summary>LoaiBienDongId. </summary>
		LoaiBienDongId,
		///<summary>MaLoaiBienDong. </summary>
		MaLoaiBienDong,
		///<summary>TenLoaiBienDong. </summary>
		TenLoaiBienDong,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: LoaiGiayTo.</summary>
	public enum LoaiGiayToFieldIndex
	{
		///<summary>LoaiGiayToId. </summary>
		LoaiGiayToId,
		///<summary>MaLoaiGiayTo. </summary>
		MaLoaiGiayTo,
		///<summary>TenLoaiGiayTo. </summary>
		TenLoaiGiayTo,
		///<summary>TypeIndex. </summary>
		TypeIndex,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: NguoiDung.</summary>
	public enum NguoiDungFieldIndex
	{
		///<summary>DiaChiEmail. </summary>
		DiaChiEmail,
		///<summary>GioiTinh. </summary>
		GioiTinh,
		///<summary>HoTenNguoiDung. </summary>
		HoTenNguoiDung,
		///<summary>MatKhau. </summary>
		MatKhau,
		///<summary>NguoiDungId. </summary>
		NguoiDungId,
		///<summary>SoDienThoai. </summary>
		SoDienThoai,
		///<summary>TenDangNhap. </summary>
		TenDangNhap,
		///<summary>VaiTro. </summary>
		VaiTro,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: ThongTinHoSo.</summary>
	public enum ThongTinHoSoFieldIndex
	{
		///<summary>ChiTietHoSo. </summary>
		ChiTietHoSo,
		///<summary>ChuyenVienId. </summary>
		ChuyenVienId,
		///<summary>ChuyenVienKiemTra. </summary>
		ChuyenVienKiemTra,
		///<summary>CongTyDoVe. </summary>
		CongTyDoVe,
		///<summary>CongTyDoVeId. </summary>
		CongTyDoVeId,
		///<summary>GhiChu. </summary>
		GhiChu,
		///<summary>GioiTinhNguoiNop. </summary>
		GioiTinhNguoiNop,
		///<summary>HoSoMoiNhat. </summary>
		HoSoMoiNhat,
		///<summary>HoTen. </summary>
		HoTen,
		///<summary>KhoaChaId. </summary>
		KhoaChaId,
		///<summary>LichSuCapNhat. </summary>
		LichSuCapNhat,
		///<summary>LoaiBienDongId. </summary>
		LoaiBienDongId,
		///<summary>NgayChinhSua. </summary>
		NgayChinhSua,
		///<summary>NgayHenTra. </summary>
		NgayHenTra,
		///<summary>NgayKiemTraNoiNghiep. </summary>
		NgayKiemTraNoiNghiep,
		///<summary>NgayNop. </summary>
		NgayNop,
		///<summary>NgayTraHoSo. </summary>
		NgayTraHoSo,
		///<summary>NguoiDungId. </summary>
		NguoiDungId,
		///<summary>NguoiNopHoSo. </summary>
		NguoiNopHoSo,
		///<summary>PhiDoVe. </summary>
		PhiDoVe,
		///<summary>PhiThamDinh. </summary>
		PhiThamDinh,
		///<summary>SoBanVe. </summary>
		SoBanVe,
		///<summary>SoBienNhan. </summary>
		SoBienNhan,
		///<summary>SoGiayTo. </summary>
		SoGiayTo,
		///<summary>SoGiayToNguoiNop. </summary>
		SoGiayToNguoiNop,
		///<summary>SoHieuGiayChungNhan. </summary>
		SoHieuGiayChungNhan,
		///<summary>SoHieuToBanDo. </summary>
		SoHieuToBanDo,
		///<summary>SoThuTuThua. </summary>
		SoThuTuThua,
		///<summary>ThongTinHoSoId. </summary>
		ThongTinHoSoId,
		///<summary>XaId. </summary>
		XaId,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Tinh.</summary>
	public enum TinhFieldIndex
	{
		///<summary>MaTinh. </summary>
		MaTinh,
		///<summary>TenTinh. </summary>
		TenTinh,
		///<summary>TinhId. </summary>
		TinhId,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Xa.</summary>
	public enum XaFieldIndex
	{
		///<summary>HuyenId. </summary>
		HuyenId,
		///<summary>MaXa. </summary>
		MaXa,
		///<summary>TenXa. </summary>
		TenXa,
		///<summary>XaId. </summary>
		XaId,
		/// <summary></summary>
		AmountOfFields
	}



	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>CauHinh</summary>
		CauHinhEntity,
		///<summary>ChuyenVien</summary>
		ChuyenVienEntity,
		///<summary>CongTyDoVe</summary>
		CongTyDoVeEntity,
		///<summary>Huyen</summary>
		HuyenEntity,
		///<summary>LoaiBienDong</summary>
		LoaiBienDongEntity,
		///<summary>LoaiGiayTo</summary>
		LoaiGiayToEntity,
		///<summary>NguoiDung</summary>
		NguoiDungEntity,
		///<summary>ThongTinHoSo</summary>
		ThongTinHoSoEntity,
		///<summary>Tinh</summary>
		TinhEntity,
		///<summary>Xa</summary>
		XaEntity
	}


	#region Custom ConstantsEnums Code
	
	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END
	
	#endregion

	#region Included code

	#endregion
}

